# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_mep.tasks import get_previous_period as get_previous_period

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_mep.tasks import (
    extract_voltage_columns as extract_voltage_columns,
)
from ecoscope_workflows_ext_mep.tasks import (
    generate_subject_voltage_chart as generate_subject_voltage_chart,
)
from ecoscope_workflows_ext_ste.tasks import (
    dataframe_column_first_unique_str as dataframe_column_first_unique_str,
)
from ecoscope_workflows_ext_ste.tasks import zip_groupbykey as zip_groupbykey

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "subject_group_var": [],
        "subject_observations": ["er_client_name", "time_range", "subject_group_var"],
        "rename_subject_reloc": ["subject_observations"],
        "get_custom_previous_period": ["time_range"],
        "previous_subject_observations": [
            "er_client_name",
            "get_custom_previous_period",
            "subject_group_var",
        ],
        "rename_previous_subject_reloc": ["previous_subject_observations"],
        "extract_current_voltage": ["subject_observations"],
        "extract_previous_voltage": ["previous_subject_observations"],
        "split_current_relocs": ["extract_current_voltage", "groupers"],
        "split_previous_relocs": ["extract_previous_voltage", "groupers"],
        "get_unique_subject_name": ["split_current_relocs"],
        "zip_current_prev_name": [
            "split_current_relocs",
            "split_previous_relocs",
            "get_unique_subject_name",
        ],
        "generate_subject_voltage": ["time_range", "zip_current_prev_name"],
        "zip_html_unique": ["generate_subject_voltage", "get_unique_subject_name"],
        "persist_collar_html": ["zip_html_unique"],
        "collared_voltage_widget": ["persist_collar_html"],
        "grouped_collared_widget": ["collared_voltage_widget"],
        "collar_voltage_dashboard": [
            "workflow_details",
            "grouped_collared_widget",
            "time_range",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": [
                    {
                        "index_name": "extra__subject__name",
                    },
                ],
            }
            | (params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "subject_group_var": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("subject_group_var")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("subject_group_var") or {}),
            method="call",
        ),
        "subject_observations": Node(
            async_task=get_subjectgroup_observations.validate()
            .set_task_instance_id("subject_observations")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "filter": "clean",
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "subject_group_name": DependsOn("subject_group_var"),
                "raise_on_empty": False,
                "include_details": True,
                "include_subjectsource_details": True,
            }
            | (params_dict.get("subject_observations") or {}),
            method="call",
        ),
        "rename_subject_reloc": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_subject_reloc")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "raise_if_not_found": True,
                "df": DependsOn("subject_observations"),
                "rename_columns": {
                    "extra__subject__name": "name",
                },
            }
            | (params_dict.get("rename_subject_reloc") or {}),
            method="call",
        ),
        "get_custom_previous_period": Node(
            async_task=get_previous_period.validate()
            .set_task_instance_id("get_custom_previous_period")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_custom_previous_period") or {}),
            method="call",
        ),
        "previous_subject_observations": Node(
            async_task=get_subjectgroup_observations.validate()
            .set_task_instance_id("previous_subject_observations")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "filter": "clean",
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("get_custom_previous_period"),
                "subject_group_name": DependsOn("subject_group_var"),
                "raise_on_empty": False,
                "include_details": True,
                "include_subjectsource_details": True,
            }
            | (params_dict.get("previous_subject_observations") or {}),
            method="call",
        ),
        "rename_previous_subject_reloc": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_previous_subject_reloc")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "raise_if_not_found": True,
                "df": DependsOn("previous_subject_observations"),
                "rename_columns": {
                    "extra__subject__name": "name",
                },
            }
            | (params_dict.get("rename_previous_subject_reloc") or {}),
            method="call",
        ),
        "extract_current_voltage": Node(
            async_task=extract_voltage_columns.validate()
            .set_task_instance_id("extract_current_voltage")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocs": DependsOn("subject_observations"),
            }
            | (params_dict.get("extract_current_voltage") or {}),
            method="call",
        ),
        "extract_previous_voltage": Node(
            async_task=extract_voltage_columns.validate()
            .set_task_instance_id("extract_previous_voltage")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocs": DependsOn("previous_subject_observations"),
            }
            | (params_dict.get("extract_previous_voltage") or {}),
            method="call",
        ),
        "split_current_relocs": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_current_relocs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_current_voltage"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_current_relocs") or {}),
            method="call",
        ),
        "split_previous_relocs": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_previous_relocs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_previous_voltage"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_previous_relocs") or {}),
            method="call",
        ),
        "get_unique_subject_name": Node(
            async_task=dataframe_column_first_unique_str.validate()
            .set_task_instance_id("get_unique_subject_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "extra__subject__name",
            }
            | (params_dict.get("get_unique_subject_name") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_current_relocs"),
            },
        ),
        "zip_current_prev_name": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_current_prev_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("split_current_relocs"),
                    DependsOn("split_previous_relocs"),
                    DependsOn("get_unique_subject_name"),
                ],
            }
            | (params_dict.get("zip_current_prev_name") or {}),
            method="call",
        ),
        "generate_subject_voltage": Node(
            async_task=generate_subject_voltage_chart.validate()
            .set_task_instance_id("generate_subject_voltage")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("generate_subject_voltage") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["subject_df", "previous_subject_df", "subject_name"],
                "argvalues": DependsOn("zip_current_prev_name"),
            },
        ),
        "zip_html_unique": Node(
            async_task=zip_groupbykey.validate()
            .set_task_instance_id("zip_html_unique")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "sequences": [
                    DependsOn("generate_subject_voltage"),
                    DependsOn("get_unique_subject_name"),
                ],
            }
            | (params_dict.get("zip_html_unique") or {}),
            method="call",
        ),
        "persist_collar_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_collar_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_collar_html") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text", "filename_suffix"],
                "argvalues": DependsOn("zip_html_unique"),
            },
        ),
        "collared_voltage_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("collared_voltage_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Collar Voltage",
            }
            | (params_dict.get("collared_voltage_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_collar_html"),
            },
        ),
        "grouped_collared_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_collared_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("collared_voltage_widget"),
            }
            | (params_dict.get("grouped_collared_widget") or {}),
            method="call",
        ),
        "collar_voltage_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("collar_voltage_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("grouped_collared_widget"),
                ],
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("collar_voltage_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
