# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_mep.tasks import (
    extract_voltage_columns as extract_voltage_columns,
)
from ecoscope_workflows_ext_mep.tasks import (
    generate_subject_voltage_chart as generate_subject_voltage_chart,
)
from ecoscope_workflows_ext_mep.tasks import get_previous_period as get_previous_period
from ecoscope_workflows_ext_ste.tasks import (
    dataframe_column_first_unique_str as dataframe_column_first_unique_str,
)
from ecoscope_workflows_ext_ste.tasks import zip_groupbykey as zip_groupbykey

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "extra__subject__name"}],
            **(params_dict.get("groupers") or {}),
        )
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    subject_group_var = (
        set_string_var.validate()
        .set_task_instance_id("subject_group_var")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("subject_group_var") or {}))
        .call()
    )

    subject_observations = (
        get_subjectgroup_observations.validate()
        .set_task_instance_id("subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client_name,
            time_range=time_range,
            subject_group_name=subject_group_var,
            raise_on_empty=False,
            include_details=True,
            include_subjectsource_details=True,
            **(params_dict.get("subject_observations") or {}),
        )
        .call()
    )

    rename_subject_reloc = (
        map_columns.validate()
        .set_task_instance_id("rename_subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            df=subject_observations,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"extra__subject__name": "name"},
            **(params_dict.get("rename_subject_reloc") or {}),
        )
        .call()
    )

    get_custom_previous_period = (
        get_previous_period.validate()
        .set_task_instance_id("get_custom_previous_period")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_range=time_range,
            **(params_dict.get("get_custom_previous_period") or {}),
        )
        .call()
    )

    previous_subject_observations = (
        get_subjectgroup_observations.validate()
        .set_task_instance_id("previous_subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client_name,
            time_range=get_custom_previous_period,
            subject_group_name=subject_group_var,
            raise_on_empty=False,
            include_details=True,
            include_subjectsource_details=True,
            **(params_dict.get("previous_subject_observations") or {}),
        )
        .call()
    )

    rename_previous_subject_reloc = (
        map_columns.validate()
        .set_task_instance_id("rename_previous_subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            df=previous_subject_observations,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"extra__subject__name": "name"},
            **(params_dict.get("rename_previous_subject_reloc") or {}),
        )
        .call()
    )

    extract_current_voltage = (
        extract_voltage_columns.validate()
        .set_task_instance_id("extract_current_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocs=subject_observations,
            **(params_dict.get("extract_current_voltage") or {}),
        )
        .call()
    )

    extract_previous_voltage = (
        extract_voltage_columns.validate()
        .set_task_instance_id("extract_previous_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocs=previous_subject_observations,
            **(params_dict.get("extract_previous_voltage") or {}),
        )
        .call()
    )

    split_current_relocs = (
        split_groups.validate()
        .set_task_instance_id("split_current_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_current_voltage,
            groupers=groupers,
            **(params_dict.get("split_current_relocs") or {}),
        )
        .call()
    )

    split_previous_relocs = (
        split_groups.validate()
        .set_task_instance_id("split_previous_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_previous_voltage,
            groupers=groupers,
            **(params_dict.get("split_previous_relocs") or {}),
        )
        .call()
    )

    get_unique_subject_name = (
        dataframe_column_first_unique_str.validate()
        .set_task_instance_id("get_unique_subject_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="extra__subject__name",
            **(params_dict.get("get_unique_subject_name") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_current_relocs)
    )

    zip_current_prev_name = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_current_prev_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[
                split_current_relocs,
                split_previous_relocs,
                get_unique_subject_name,
            ],
            **(params_dict.get("zip_current_prev_name") or {}),
        )
        .call()
    )

    generate_subject_voltage = (
        generate_subject_voltage_chart.validate()
        .set_task_instance_id("generate_subject_voltage")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_range=time_range, **(params_dict.get("generate_subject_voltage") or {})
        )
        .mapvalues(
            argnames=["subject_df", "previous_subject_df", "subject_name"],
            argvalues=zip_current_prev_name,
        )
    )

    zip_html_unique = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_html_unique")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[generate_subject_voltage, get_unique_subject_name],
            **(params_dict.get("zip_html_unique") or {}),
        )
        .call()
    )

    persist_collar_html = (
        persist_text.validate()
        .set_task_instance_id("persist_collar_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_collar_html") or {}),
        )
        .mapvalues(argnames=["text", "filename_suffix"], argvalues=zip_html_unique)
    )

    collared_voltage_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("collared_voltage_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Collar Voltage", **(params_dict.get("collared_voltage_widget") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_collar_html)
    )

    grouped_collared_widget = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_collared_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=collared_voltage_widget,
            **(params_dict.get("grouped_collared_widget") or {}),
        )
        .call()
    )

    collar_voltage_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("collar_voltage_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[grouped_collared_widget],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("collar_voltage_dashboard") or {}),
        )
        .call()
    )

    return collar_voltage_dashboard
