# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Source Voltage
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_mep.tasks import (
    extract_voltage_columns as extract_voltage_columns,
)
from ecoscope_workflows_ext_mep.tasks import (
    generate_source_voltage_report as generate_source_voltage_report,
)
from ecoscope_workflows_ext_mep.tasks import (
    generate_subject_voltage_chart as generate_subject_voltage_chart,
)
from ecoscope_workflows_ext_mep.tasks import get_previous_period as get_previous_period
from ecoscope_workflows_ext_ste.tasks import (
    dataframe_column_first_unique_str as dataframe_column_first_unique_str,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_file_path as get_file_path
from ecoscope_workflows_ext_ste.tasks import zip_groupbykey as zip_groupbykey

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Define analysis time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Configure grouping strategy

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[{"index_name": "name"}], **groupers_params)
    .call()
)


# %% [markdown]
# ## Connect to earth ranger

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

subject_group_var_params = dict(
    var=...,
)

# %%
# call the task


subject_group_var = (
    set_string_var.set_task_instance_id("subject_group_var")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**subject_group_var_params)
    .call()
)


# %% [markdown]
# ## Get subject group observations

# %%
# parameters

subject_observations_params = dict()

# %%
# call the task


subject_observations = (
    get_subjectgroup_observations.set_task_instance_id("subject_observations")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        filter="clean",
        client=er_client_name,
        time_range=time_range,
        subject_group_name=subject_group_var,
        raise_on_empty=False,
        include_details=True,
        include_subjectsource_details=True,
        **subject_observations_params,
    )
    .call()
)


# %% [markdown]
# ## Rename reloc columns

# %%
# parameters

rename_subject_reloc_params = dict()

# %%
# call the task


rename_subject_reloc = (
    map_columns.set_task_instance_id("rename_subject_reloc")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        df=subject_observations,
        drop_columns=[],
        retain_columns=[],
        rename_columns={"extra__subject__name": "name"},
        **rename_subject_reloc_params,
    )
    .call()
)


# %% [markdown]
# ## Get previous period

# %%
# parameters

get_custom_previous_period_params = dict()

# %%
# call the task


get_custom_previous_period = (
    get_previous_period.set_task_instance_id("get_custom_previous_period")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_custom_previous_period_params)
    .call()
)


# %% [markdown]
# ## Get subject group observations for previous relocs

# %%
# parameters

previous_subject_observations_params = dict()

# %%
# call the task


previous_subject_observations = (
    get_subjectgroup_observations.set_task_instance_id("previous_subject_observations")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        filter="clean",
        client=er_client_name,
        time_range=get_custom_previous_period,
        subject_group_name=subject_group_var,
        raise_on_empty=False,
        include_details=True,
        include_subjectsource_details=True,
        **previous_subject_observations_params,
    )
    .call()
)


# %% [markdown]
# ## Rename previous reloc columns

# %%
# parameters

rename_previous_subject_reloc_params = dict()

# %%
# call the task


rename_previous_subject_reloc = (
    map_columns.set_task_instance_id("rename_previous_subject_reloc")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        df=previous_subject_observations,
        drop_columns=[],
        retain_columns=[],
        rename_columns={"extra__subject__name": "name"},
        **rename_previous_subject_reloc_params,
    )
    .call()
)


# %% [markdown]
# ## Extract current voltage columns

# %%
# parameters

extract_current_voltage_params = dict()

# %%
# call the task


extract_current_voltage = (
    extract_voltage_columns.set_task_instance_id("extract_current_voltage")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocs=rename_subject_reloc, **extract_current_voltage_params)
    .call()
)


# %% [markdown]
# ## Extract previous voltage columns

# %%
# parameters

extract_previous_voltage_params = dict()

# %%
# call the task


extract_previous_voltage = (
    extract_voltage_columns.set_task_instance_id("extract_previous_voltage")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocs=rename_previous_subject_reloc, **extract_previous_voltage_params)
    .call()
)


# %% [markdown]
# ## Split current reloc groups

# %%
# parameters

split_current_relocs_params = dict()

# %%
# call the task


split_current_relocs = (
    split_groups.set_task_instance_id("split_current_relocs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_current_voltage, groupers=groupers, **split_current_relocs_params
    )
    .call()
)


# %% [markdown]
# ## Split previous reloc groups

# %%
# parameters

split_previous_relocs_params = dict()

# %%
# call the task


split_previous_relocs = (
    split_groups.set_task_instance_id("split_previous_relocs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_previous_voltage, groupers=groupers, **split_previous_relocs_params
    )
    .call()
)


# %% [markdown]
# ## Get unique subject name

# %%
# parameters

get_unique_subject_name_params = dict()

# %%
# call the task


get_unique_subject_name = (
    dataframe_column_first_unique_str.set_task_instance_id("get_unique_subject_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column_name="name", **get_unique_subject_name_params)
    .mapvalues(argnames=["df"], argvalues=split_current_relocs)
)


# %% [markdown]
# ## Zip values

# %%
# parameters

zip_current_prev_name_params = dict()

# %%
# call the task


zip_current_prev_name = (
    zip_groupbykey.set_task_instance_id("zip_current_prev_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[
            split_current_relocs,
            split_previous_relocs,
            get_unique_subject_name,
        ],
        **zip_current_prev_name_params,
    )
    .call()
)


# %% [markdown]
# ## Generate subject collar voltage

# %%
# parameters

generate_subject_voltage_params = dict()

# %%
# call the task


generate_subject_voltage = (
    generate_subject_voltage_chart.set_task_instance_id("generate_subject_voltage")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **generate_subject_voltage_params)
    .mapvalues(
        argnames=["subject_df", "previous_subject_df", "subject_name"],
        argvalues=zip_current_prev_name,
    )
)


# %% [markdown]
# ## Zip html with unique subject

# %%
# parameters

zip_html_unique_params = dict()

# %%
# call the task


zip_html_unique = (
    zip_groupbykey.set_task_instance_id("zip_html_unique")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        sequences=[generate_subject_voltage, get_unique_subject_name],
        **zip_html_unique_params,
    )
    .call()
)


# %% [markdown]
# ## Persist collar voltage text as html

# %%
# parameters

persist_collar_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_collar_html = (
    persist_text.set_task_instance_id("persist_collar_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **persist_collar_html_params
    )
    .mapvalues(argnames=["text", "filename_suffix"], argvalues=zip_html_unique)
)


# %% [markdown]
# ## Convert collared plot html to png

# %%
# parameters

convert_collared_png_params = dict()

# %%
# call the task


convert_collared_png = (
    html_to_png.set_task_instance_id("convert_collared_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 20,
            "max_concurrent_pages": 1,
        },
        **convert_collared_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_collar_html)
)


# %% [markdown]
# ## Create widget for collar voltage plot

# %%
# parameters

collared_voltage_widget_params = dict()

# %%
# call the task


collared_voltage_widget = (
    create_map_widget_single_view.set_task_instance_id("collared_voltage_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Collar Voltage", **collared_voltage_widget_params)
    .map(argnames=["view", "data"], argvalues=persist_collar_html)
)


# %% [markdown]
# ## Merge collar voltage plot widgets

# %%
# parameters

grouped_collared_widget_params = dict()

# %%
# call the task


grouped_collared_widget = (
    merge_widget_views.set_task_instance_id("grouped_collared_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(widgets=collared_voltage_widget, **grouped_collared_widget_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

logo_path_params = dict(
    input_method=...,
)

# %%
# call the task


logo_path = (
    get_file_path.set_task_instance_id("logo_path")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **logo_path_params)
    .call()
)


# %% [markdown]
# ## Download collar voltage template

# %%
# parameters

persist_template_params = dict()

# %%
# call the task


persist_template = (
    fetch_and_persist_file.set_task_instance_id("persist_template")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        url="https://www.dropbox.com/scl/fi/ywlnnl3dvnqncrh2uzif0/source_voltage_report.docx?rlkey=2m0dtzr6hf5ll2sn3yaq8z5rt&st=avvjku8o&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        retries=3,
        unzip=False,
        **persist_template_params,
    )
    .call()
)


# %% [markdown]
# ## Persist word doc

# %%
# parameters

persist_word_doc_params = dict()

# %%
# call the task


persist_word_doc = (
    generate_source_voltage_report.set_task_instance_id("persist_word_doc")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        org_logo_path=logo_path,
        report_period=time_range,
        prepared_by="Ecoscope",
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename="source_voltage_report.docx",
        template_path=persist_template,
        **persist_word_doc_params,
    )
    .call()
)


# %% [markdown]
# ## Collar Voltage widget

# %%
# parameters

collar_voltage_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


collar_voltage_dashboard = (
    gather_dashboard.set_task_instance_id("collar_voltage_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[grouped_collared_widget],
        time_range=time_range,
        groupers=groupers,
        **collar_voltage_dashboard_params,
    )
    .call()
)
