# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectGroupVar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(..., title="")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class DownloadFile(BaseModel):
    url: str = Field(..., description="URL to download a file", title="URL")


class LocalFile(BaseModel):
    file_path: str = Field(
        ..., description="Path to a local file", title="Local file path"
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class LogoPath(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define analysis time range",
    )
    er_client_name: Optional[ErClientName] = Field(
        None, title="Connect to earth ranger"
    )
    subject_group_var: Optional[SubjectGroupVar] = Field(None, title="")
    logo_path: Optional[LogoPath] = Field(None, title="")
